
CREATE TABLE Usuarios(
ID INT PRIMARY KEY IDENTITY (1,1),
Nombre NVARCHAR(50) NOT NULL,
Apellido NVARCHAR(50) NOT NULL,
Email NVARCHAR(100) NOT NULL,
Usuario NVARCHAR(100) NOT NULL,
Contraseña NVARCHAR(100) NOT NULL,
FechaRegistro DATETIME DEFAULT GETDATE(),
Activo BIT DEFAULT 1

);

CREATE TABLE Tareas(
ID INT PRIMARY KEY IDENTITY (1,1),
Titulo NVARCHAR(50) NOT NULL,
Descripcion NVARCHAR (500) NOT NULL,
Estado NVARCHAR(50) DEFAULT 'Pendiente'
		CHECK (Estado IN ('Pendiente','En Progreso','Completado','Cancelada')),
Prioridad INT DEFAULT 3 CHECK (Prioridad BETWEEN 1 AND 5),
FechaCreacion DATETIME DEFAULT GETDATE(),
FechaVencimiento DATETIME,
UsuarioID INT NOT NULL,
CONSTRAINT FK_Tareas_Usuarios FOREIGN KEY (UsuarioID)
	REFERENCES Usuarios(ID) ON DELETE CASCADE
);

CREATE TABLE Resgitro_Actividad(
ID INT PRIMARY KEY IDENTITY(1,1),
TareaID INT NOT NULL,
UsuarioID INT NOT NULL,
Accion NVARCHAR (100) NOT NULL,
Descripcion NVARCHAR (500),
FechaRegistro DATETIME DEFAULT GETDATE()
	CONSTRAINT FK_Registro_Tareas FOREIGN KEY (TareaID)
		REFERENCES Tareas(ID),
	CONSTRAINT FK_Registro_Usuarios FOREIGN KEY (UsuarioID)
		REFERENCES Usuarios(ID)
);